### ISSUE TITLE
Setup on Linux

### ISSUE THREAD

**Issue by rishiba** [asingh33/SupervisedChromeTrex#1]
Does this code work on Linux. I tried running the code and am facing this issue. I installed quartz module but it is still giving me errors.

I downloaded quartz from ```https://pypi.python.org/pypi/quartz/0.0.1.dev0```

_$ KERAS_BACKEND=theano python main.py 
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import Quartz.CoreGraphics as CG
ImportError: No module named Quartz.CoreGraphics_

I am using the following version.

_$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"_

**Comment by asingh33** [comment]
Hey man,
I have replied you on FB messenger. But copying it here as well for others.

In order to support Linux I believe you need to mainly modify code in main.py
Particularly these ones:
- Screencapture module need to be modified as I used Quartz.CoreGraphics lib which I think is supported only on Mac. For Linux, alternatively you can use ImageGrab module from PIL (Pillow) lib. All you need to do is screen capture. 
- Another code change will be required for kbAction(). I used Apple action script to send keyboard inputs to Chrome browser. You can use may be PyAutoGui for linux - https://pyautogui.readthedocs.io/en/latest/introduction.html#examples
